export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const SIGNED_IN = 'SIGNED_IN'
export const LOGOUT = 'LOGOUT'
export const LOGOUTED = 'LOGOUTED'
export const SIGN_INGOOGLE = 'SIGN_INGOOGLE'
export const FORGET = 'FORGET'

export const SETALERT = 'SETALERT'
export const RESETALERT = 'RESETALERT'
